---
title: " Analyzing archaeological data using R"
---

Welcome to [AES_707](https://is.muni.cz/predmet/phil/AES_707) Statistics seminar
for archaeology students at the [Department of Archaeology and Museology](https://archeo-muzeo.phil.muni.cz/),
Masaryk University.
The course is taught by **Petr Pajdla** and **Peter Tkáč**.

Information given here applies to spring semester 2024, the page will be
continuously updated throughout the semester.
The course was taught also in 2022 and 2020.

- Each Wednesday, 12:00 -- 13:40 (except 17th April -- why?).
- Room [L11](https://www.phil.muni.cz/o-nas/kde-nas-najdete/kancelar-28397)
  (computers are provided in the room, you can use your own laptop though).
- 3 ECTS credits, i.e.  approx. 75 h. of workload, seminars take up approx. 25 h.
- You will work on a [project](#project) of your own to complete the
  course.

### Information on assessment
To pass the course, you have to finish and submit a report on your [project](#project).
There are four assessment dates:
- **2nd June**,
- **16th June**,
- **30th June**,
- 8th September - corrections only!

By the given date, please send us your project report.
We will go through the reports and either **return it to you with notes** what to
correct etc. or find it good enough to pass the course.
If you need any help, please let us know in advance!
