---
title: "Resources"
---

Here is a non exhaustive list of resources and links we find useful.
These cover various topics and most are openly available online.
We expect you to be creative and search (not only) through these resources if
you get stuck with your project or find any topics difficult to understand.
If you find it hard to get access to any of the articles or books mentioned here,
do not hesitate contacting us. Definitely do not use websites like Sci-Hub or
Library Genesis that seem to provide scientific knowledge to all. The King of
the Potato People prohibits this.

## Quantitative and digital archaeology

- Carlson, D. L. 2017: *Quantitative Methods in Archaeology Using R.*
  Cambridge: Cambridge University Press.
- VanPool, TL and Leonard, RD. 2011. *Quantitative analysis in archaeology.* Chichester:   Wiley-Blackwell.
- Drennan, R. D. 2010: *Statistics for Archaeologists: A common sense approach.*
  New York: Springer.
- Baxter, M. 2003: *Statistics in Archaeology*. London: Wiley.
- Fletcher, M., Lock, G. R. 1994: *Digging Numbers: Elementary statistics for archaeologists.*
  Oxford: Oxbow.
- Shennan, S. 1988: *Quantifying Archaeology.* Edinburgh: Edinburgh University Press.

<!--
- [Open Digital Archaeology Textbook](https://o-date.github.io/) by Shawn Graham et al.
-->

<!--
### Statistics
- [An Introduction to Statistical Learning](https://www.statlearning.com/) by
  Gareth James, Daniela Witten, Trevor Hastie and Rob Tibshirani.
  Great resource to learn more, way advanced than how the subject is explained in
  this course though.
-->

## R programming language and environment

- [R for Data Science](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund (2nd Ed.).
- [Data Visualization. A practical introduction](https://socviz.co/) by Kieran Healy.
- [CRAN Task View](https://github.com/benmarwick/ctv-archaeology) is a list of
  R packages useful in archaeology maintained by Ben Marwick.
  There is also a list of articles using R in the analysis with data and code
  published.

### Where to look for help

- [Posit/RStudio cheatsheets](https://posit.co/resources/cheatsheets/), especially
  data visualization, transformation, tidying and import cheatsheets will come in useful.
- Search through [Stack Overflow](https://stackoverflow.com/questions/tagged/r).
  Find some tips on asking good questions and providing minimal reproducible examples
  in this [thread](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example).
  
### Data visualizations 

- Choosing proper graph for the data and message you want to communicate can be difficult, have a look at some of galeries of various graphs: [Visual vocabulary by Financial Times](ft.com/vocabulary), [From Data to Viz](https://www.data-to-viz.com) website or [The Data Visualisation Catalogue](https://datavizcatalogue.com/).
- Or go for sites with graphs created in R directly (with code): [R Graph Gallery](https://r-graph-gallery.com/index.html) or [R Charts](https://r-charts.com/).
- Choosing right colors for your graphs and maps can be difficult, have a look at the [Color Brewer](https://colorbrewer2.org) website that offers many great color palettes.

## Reproducibility

- Marwick, B. 2017: Computational Reproducibility in Archaeological Research:
  Basic Principles and a Case Study of Their Implementation.
  *Journal of Archaeological Method and Theory* 24(2): 424–450.
  DOI: [10.1007/s10816-015-9272-9](https://doi.org/10.1007/s10816-015-9272-9).
- Marwick, B., Boettiger, C. and Mullen, L. 2018: Packaging Data Analytical Work
  Reproducibly Using R (and Friends). *The American Statistician* 72(1): 80–88.
  DOI: [10.1080/00031305.2017.1375986](https://doi.org/10.1080/00031305.2017.1375986).

### Data management

- Karl Broman's [guide](https://kbroman.org/dataorg/) on how to organize data in
  spreadsheets. The same as an article, DOI: [https://doi.org/gdz6cm](https://doi.org/gdz6cm).
- Jenny Bryan's [slides](http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf) on naming things.
- Hadley Wickham's paper on tidy data, DOI: [https://doi.org/10.18637/jss.v059.i10](https://doi.org/10.18637/jss.v059.i10).

### RMarkdown/Quarto and scientific writing

- *British Ecological Society* has a nice series of [Guides to Better Science](https://www.britishecologicalsociety.org/publications/guides-to/)
  covering various topics including [Reproducible Code](https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf?utm_source=web&utm_medium=web&utm_campaign=better_science)
  and [Data Management](https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Data-Management-2019.pdf?utm_source=web&utm_medium=web&utm_campaign=better_science).
- A short [guide](https://github.com/benmarwick/atom-for-scholarly-writing-with-markdown)
  by Ben Marwick on how to setup Atom (this could be any text editor) and Zotero
  (citation management software).
- [The Plain Person’s Guide to Plain Text Social Science](https://plain-text.co/)
  by Kieran Healy.

## R as a GIS and spatial analysis

- [Geocomputation with R](https://geocompr.robinlovelace.net/index.html) book by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow.
- [Spatial Data Science](https://r-spatial.org/book/) book by Edzer Pebesma and Roger Bivand.

## Other links and tools

- [Open-archaeo](https://open-archaeo.info/) is a list of open source archaeological
  software and resources maintained by Zack Batist.
  
## Installing R and RStudio

There is a [comprehensive guide on how to install R and RStudio](https://rstudio-education.github.io/hopr/starting.html) in the [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) book by Garrett Grolemund.

If you do not want to install R on your machine, there are several online compilers or [Posit Cloud](https://posit.cloud/).
