---
title: "Schedule"
format:
  html: default
  pdf: default
---

## 2025 

The course takes place once in two weeks, on **odd Wednesdays 12:00 -- 15:40** (except 19. 11. -- *Reading week*).

::: {.column-page-right}

| #       | Date    | Topics | Notes |
|---------|---------|--------|-------|
| 1.      | 24. 9.  | [Introduction](lect/w01/intro.qmd), [*Tidy data*](lect/w01/tidy.qmd) and [Intro to coding in R](lect/w01/intro2coding.qmd)| [{{< bi file-earmark-arrow-down >}} fake_graves.R](lect/w01/code/fake_graves.R) |
| 2.      | 8. 10.  | [Basic workflows](lect/w02/basics.qmd), [plotting with `qqplot2`](lect/w02/ggplot.amd), [Descriptive stats](lect/w02/describing.qmd), [Data viz](lect/w02/visualizing.qmd) and [Relationships](lect/w02/relations.qmd)  |  |
| 3.      | 22. 10. | [Intro](lect/w03/intro.qmd), [Tidy data](lect/w03/tidy_data.qmd) & [Transformations](lect/w03/transformation.qmd)  | Synthetic BA burial ground [exercise](lect/w03/exc.qmd): <br> [{{< bi file-earmark-arrow-down >}} graves.csv](lect/w03/data/graves.csv) & [{{< bi file-earmark-arrow-down >}} artefacts.csv](lect/w03/data/artefacts.csv) |
| 4.      | 5. 11.  | [Joins](lect/w04/joins.qmd), [Correspondence analysis](lect/w04/ca.qmd) and [Distances & similarity](lect/w04/dist.qmd) | Eneolithic/BA burials data ([{{< bi file-earmark-arrow-down >}} burials.csv](lect/w04/data/burials.csv)) |
| -       | 19. 11. | *Reading week* |  |
| 5.      | 3. 12.  | [Clustering](lect/w05/clust.qmd) | [PCA exercise](lect/w05/exc.qmd): [{{< bi file-earmark-arrow-down >}} artefacts.csv](lect/w05/data/artefacts.csv) and<br> [{{< bi file-earmark-arrow-down >}} bronze_composition.xlsx](lect/w05/data/bronze_composition.xlsx)|
| 6.      | 17. 12. | [Showcase of our projects](lect/w06/show.qmd) |  |

:::

## Archive 

### Spring 2024

The course takes place each **Wednesday 12:00 -- 13:40 in L11**, except 17. 4. (reading week), 1. 5. and 8. 5. (holidays). 

::: {.column-page-right}

| Lecture | Date   | Topics | Notes |
|---------|--------|--------|-------|
| 1.      | 21. 2. | [Introduction](lect/w01/intro.qmd) and [*Tidy data*](lect/w01/tidy.qmd) | [{{< bi file-earmark-arrow-down >}} Example script](lect/w01/teaser.r) |
| 2.      | 28. 2. | [Basic coding in R](lect/w02/intro2r.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset](lect/w02/data/dartpoints.csv) |
| 3.      | 6. 3.  | [Visualization and summary of distributions](lect/w03/distribs.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset](lect/w03/data/dartpoints2.csv) |
| 4.      | 13. 3. | [Visualization and summary of relationships](lect/w04/rels.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset](lect/w04/data/bacups.csv) & [{{< bi file-earmark-arrow-down >}} Script](lect/w04/code/bacups.r) |
| 5.      | 20. 3. | [Normal distribution](lect/w05/norm.qmd) & [data manpulation with `dplyr`](lect/w05/dplyr.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset](lect/w05/data/dartpoints.csv) |
| 6.      | 27. 3. | Presenting data sets for projects & Practice | |
| 7.      | 3. 4.  | [Considering space](lect/w07/space.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset (lasoles)](lect/w07/data/LASOLES_14C_database.csv) & [{{< bi file-earmark-arrow-down >}} Solution](lect/w07/code/analysis.r) |
| 8.      | 10. 4. | [Considering time](lect/w08/time.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset (datations)](lect/w08/data/datation_mor.csv) | 
| -       | 17. 4. | *Reading week* | *Individual consultations of projects* |
| 9.      | 24. 4. | [Distances](lect/w09/dist.qmd) & [Custering](lect/w09/clust.qmd) | [{{< bi file-earmark-arrow-down >}} Dataset (dart points)](lect/w09/data/dartpoints_numeric.csv) |
| -       | 1. 5.  | *Holidays* | |
| -       | 8. 5.  | *Holidays* | |
| 10.     | 15. 5. | Dimensionality reduction: [Correspondence analysis](lect/w10/ca.qmd) | |
| 11.     | 22. 5. | [Reproducibility](lect/w11/repro.qmd) & [Table transformations](lect/w11/pivoting.qmd) | |

:::
