---
title: "Course introduction"
format:
  html: default
  revealjs:
    fontsize: 16px
    output-file: slides_intro.html
  pdf: default
---

## Objectives

- The goal of the course is to

## Prerequisites

- Not to be afraid of learning a scripting language.
- Elementary knowledge of mathematics/statistics, use these to review some of the knowledge:

    - [Khan Academy 7th grade statistics](https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-probability-statistics)
    - [Khan Academy High School statistics](https://www.khanacademy.org/math/probability)

## Basic information

- Lectures/seminars each Wednesday, 12:00 -- 13:40, room L11.
- Bring your own laptop or use the computers in the room.

### Projects

- During the course, you will work on a data analysis project of your own, see [more details here](../../project.qmd).

## Exercises

## Assignments

- Read chapters **Quantifying Archaeology** in *Quantitative Analysis in Archaeology* book by VanPool, T. L. and Leonard, R. D. (2011).
- Optionally, read **Introductions** in:

  - *Quantifying archaeology* book by Stephen Shennan, and/or
  - *Quantitative Methods in Archaeology* book by David L.
  Carlson (see [Resources](../../resources.qmd) for details).
  These give a general overview on why to use
  quantitative/computational methods in archaeology.
